<?php
/**
 * Created by PhpStorm.
 * User: chenxi
 * Date: 2017/6/12
 * Time: 14:46
 */
namespace frontend\modules\v1\models;

class SearchMovie extends \frontend\modules\v1\models\Movie{

    public function fields()
    {
        $fields =  parent::fields(); // TODO: Change the autogenerated stub

        $fields = array_merge($fields,[
            'websiteResource' => function($model){
                return $model->websiteResource;
            },
            'onlineResource' => function($model){
                return $model->onlineResource;
            },

        ]);

        return $fields;
    }

    public function extraFields()
    {
        return parent::extraFields(); // TODO: Change the autogenerated stub
    }


}