<?php
/**
 * Created by PhpStorm.
 * User: chenxi
 * Date: 2017/6/27
 * Time: 18:25
 */

namespace backend\components;

use JPush\Client;
use JPush\Exceptions\APIConnectionException;
use JPush\Exceptions\APIRequestException;
use yii\base\Object;
use yii\httpclient\Exception;

class JPush extends Object{

    protected $appKey = '74abfa4144fb540f7e8eaea9';
    protected $masterSecret = '41fbd495f168acd36dba4bb9';
    protected $_client;



    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function getClient(){
        if($this->_client == null){
            $this->_client = new Client($this->appKey,$this->masterSecret,'./log/jpush.log');
        }
        return $this->_client;
//        $this->_client = new Client($this->appKey,$this->masterSecret);

    }

    public function send($registrationID,$content){

        $push = $this->getClient()->push();

        $push->setPlatform('ios');

        $push->addRegistrationId($registrationID);

//        $push->setNotificationAlert('title test');

        $push->iosNotification($content, [
//            'sound' => 'sound',
//             'extras' => [
//                'key' => 'value'
//            ]
        ]);

        try{
            $push->send();
        }catch(APIConnectionException $e){
            throw new Exception($e);
        }catch(APIRequestException $e){
            throw new Exception($e);
        }
    }


}